name: .NET Core Desktop

on:
  push:
    branches: [ "build" ]
  pull_request:
    branches: [ "build" ]

jobs:

  build:
  
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: MouseJiggler/MouseJiggler.sln                         # Replace with your solution name, i.e. MyWpfApp.sln.

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 5.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=Release

    - name: Build
      run: dotnet build $env:Solution_Name
    - name: Publish
      run: dotnet publish $env:Solution_Name -c Release
    - name: Archive
      uses: actions/upload-artifact@v4
      with:
        path: MouseJiggler\bin\Release\net5.0-windows\win-x64\publish\*.exe